apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: expressaks 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: expressaks 
    spec:
      containers:
        - name: expressaks 
          image: wydfdevreg.azurecr.io/expressaks 
          ports:
          - containerPort: 3000